/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class NewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameEmployee = new javax.swing.JTextField();
        numberEmployee = new javax.swing.JTextField();
        emailEmployee = new javax.swing.JTextField();
        fatherNameEmployee = new javax.swing.JTextField();
        addressEmployee = new javax.swing.JTextField();
        motherNameEmployee = new javax.swing.JTextField();
        designationEmployee = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        newEmployeeSaveButton = new javax.swing.JButton();
        newEmployeeClearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 40, 30));

        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 30));

        jLabel4.setText("Email ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 30));

        jLabel5.setText("Father Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, 30));

        jLabel6.setText("Mother Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        jLabel7.setText("Permanent Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 20));

        jLabel8.setText("Designation");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, 30));
        getContentPane().add(nameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 220, 30));
        getContentPane().add(numberEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 30));
        getContentPane().add(emailEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 30));
        getContentPane().add(fatherNameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, 30));
        getContentPane().add(addressEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 220, 30));
        getContentPane().add(motherNameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 30));

        designationEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleaner", "Cook", "Security Guard" }));
        getContentPane().add(designationEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 220, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton2.setText("EXIT");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 60));

        newEmployeeSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        newEmployeeSaveButton.setText("Save");
        getContentPane().add(newEmployeeSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 90, 30));

        newEmployeeClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        newEmployeeClearButton.setText("Clear");
        getContentPane().add(newEmployeeClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressEmployee;
    private javax.swing.JComboBox<String> designationEmployee;
    private javax.swing.JTextField emailEmployee;
    private javax.swing.JTextField fatherNameEmployee;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField motherNameEmployee;
    private javax.swing.JTextField nameEmployee;
    private javax.swing.JButton newEmployeeClearButton;
    private javax.swing.JButton newEmployeeSaveButton;
    private javax.swing.JTextField numberEmployee;
    // End of variables declaration//GEN-END:variables
}
