/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class StudentFee extends javax.swing.JFrame {

    /**
     * Creates new form StudentFee
     */
    public StudentFee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amountFee = new javax.swing.JTextField();
        nameFee = new javax.swing.JTextField();
        emailFee = new javax.swing.JTextField();
        numberFee = new javax.swing.JTextField();
        roomFee = new javax.swing.JTextField();
        monthFee = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        saveFeeButton = new javax.swing.JButton();
        clearFeeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        feeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 510));
        setPreferredSize(new java.awt.Dimension(700, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        jLabel4.setText("Room Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 40));

        jLabel5.setText("Month");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 40));

        jLabel6.setText("Amount to be paid");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 40));

        jLabel7.setText("Mobile Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 40));

        jLabel8.setText("Name");
        jLabel8.setMaximumSize(new java.awt.Dimension(747, 700));
        jLabel8.setMinimumSize(new java.awt.Dimension(747, 700));
        jLabel8.setPreferredSize(new java.awt.Dimension(747, 700));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 30));

        amountFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFeeActionPerformed(evt);
            }
        });
        jPanel1.add(amountFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 310, 30));

        nameFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFeeActionPerformed(evt);
            }
        });
        jPanel1.add(nameFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, 30));

        emailFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFeeActionPerformed(evt);
            }
        });
        jPanel1.add(emailFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 310, 30));

        numberFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFeeActionPerformed(evt);
            }
        });
        jPanel1.add(numberFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 310, 30));

        roomFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomFeeActionPerformed(evt);
            }
        });
        jPanel1.add(roomFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 310, 30));

        monthFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFeeActionPerformed(evt);
            }
        });
        jPanel1.add(monthFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 310, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton1.setText("Search");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 100, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton2.setText("EXIT");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 130, 60));

        saveFeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveFeeButton.setText("Save");
        jPanel1.add(saveFeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 90, 30));

        clearFeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        clearFeeButton.setText("Clear");
        jPanel1.add(clearFeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 90, 30));

        feeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Month ", "Amount"
            }
        ));
        jScrollPane1.setViewportView(feeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 520, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(765, 700));
        jLabel2.setMinimumSize(new java.awt.Dimension(747, 700));
        jLabel2.setPreferredSize(new java.awt.Dimension(747, 700));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -200, 840, 930));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFeeActionPerformed

    private void nameFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFeeActionPerformed

    private void emailFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeeActionPerformed

    private void numberFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFeeActionPerformed

    private void roomFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomFeeActionPerformed

    private void monthFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountFee;
    private javax.swing.JButton clearFeeButton;
    private javax.swing.JTextField emailFee;
    private javax.swing.JTable feeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthFee;
    private javax.swing.JTextField nameFee;
    private javax.swing.JTextField numberFee;
    private javax.swing.JTextField roomFee;
    private javax.swing.JButton saveFeeButton;
    // End of variables declaration//GEN-END:variables
}
